import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Date;

/**
 * Class responsible for generating pdf files
 */
public class PDFGenerator {

    /**
     * A static method that generates an appropriate pdf file using the parameters provided on the input
     * @param author - a value representing the author of the pdf
     * @param pathToFile - a value representing the path to file to save
     * @param date - a value representing the date of the visit as Timestamp
     * @param comment - a value representing orthodontist comment of visit
     * @param personalData - a value representing personal data of the patient
     * @param pathToImage - a value representing the path to image
     */
    public static void createPdf(String author, String pathToFile, String date, String comment, String personalData, String pathToImage){
        Document document = new Document();
        FileOutputStream file = null;
        try {
            file = new FileOutputStream(pathToFile);
        } catch (FileNotFoundException e) {
            e.printStackTrace();
        }
        try {
            PdfWriter.getInstance(document, file);
        } catch (DocumentException e) {
            e.printStackTrace();
        }
        document.open();
        try {
            document.add(new Paragraph("A PDF file generated by the patient's service system software at:"));
        } catch (DocumentException e) {
            e.printStackTrace();
        }
        try {
            document.add(new Paragraph(new Date().toString()));
        } catch (DocumentException e) {
            e.printStackTrace();
        }
        document.addAuthor(author);
        document.addCreationDate();
        document.addCreator("Patient Service System");
        document.addTitle("Visit report of the day: " + date);

        Paragraph personalInfo = new Paragraph("Patient Report: ",new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD));
        personalInfo.add(new Paragraph(personalData,new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL)));
        try {
            document.add(personalInfo);
        } catch (DocumentException e) {
            e.printStackTrace();
        }

        Paragraph paragraphImage = new Paragraph("Last pantomography imaging: ",new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD));
        try {
            document.add(paragraphImage);
        } catch (DocumentException e) {
            e.printStackTrace();
        }
        try {
            Image image = Image.getInstance(pathToImage);
            image.scaleAbsolute(document.getPageSize().getWidth()/1.1f, document.getPageSize().getHeight()/3);
            document.add(image);
        } catch (Exception e) {
            e.printStackTrace();
        }
        Paragraph paragraph = new Paragraph("Date of the visit: ",new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD));
        paragraph.add(new Paragraph(date,new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL)));
        paragraph.add(new Paragraph("Orthodontist comment: ",new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD)));
        paragraph.add(new Paragraph(comment,new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL)));
        paragraph.add(new Paragraph(" "));
        try {
            document.add(paragraph);
        } catch (DocumentException e) {
            e.printStackTrace();
        }

        document.close();
        try {
            if (file != null) {
                file.close();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
